import type { Course, CourseModule } from "./types";

const baseDate = new Date("2026-06-09T10:00:00Z").getTime();
const daysAgo = (n: number) => new Date(baseDate - n * 86400000).toISOString();

const mod1Lessons: CourseModule["lessons"] = [
  { id: "les-1-1", title: "Pengenalan Next.js 14", type: "video", duration: 720, isFree: true, order: 1, contentUrl: "https://youtube.com/watch?v=abc1" },
  { id: "les-1-2", title: "Instalasi & Setup Project", type: "video", duration: 900, isFree: true, order: 2, contentUrl: "https://youtube.com/watch?v=abc2" },
  { id: "les-1-3", title: "Cheat Sheet: App Router", type: "pdf", duration: 300, isFree: false, order: 3, contentUrl: "/files/cheatsheet.pdf" },
  { id: "les-1-4", title: "Kuis: Dasar Next.js", type: "quiz", duration: 600, isFree: false, order: 4 },
];

const mod2Lessons: CourseModule["lessons"] = [
  { id: "les-2-1", title: "Server vs Client Components", type: "video", duration: 1080, isFree: false, order: 1, contentUrl: "https://youtube.com/watch?v=abc3" },
  { id: "les-2-2", title: "Data Fetching Patterns", type: "video", duration: 1500, isFree: false, order: 2, contentUrl: "https://youtube.com/watch?v=abc4" },
  { id: "les-2-3", title: "Resource: Dokumentasi Resmi", type: "link", duration: 0, isFree: false, order: 3, contentUrl: "https://nextjs.org/docs" },
];

const mod3Lessons: CourseModule["lessons"] = [
  { id: "les-3-1", title: "Membuat REST API", type: "video", duration: 1320, isFree: false, order: 1, contentUrl: "https://youtube.com/watch?v=abc5" },
  { id: "les-3-2", title: "Authentication dengan NextAuth", type: "video", duration: 1800, isFree: false, order: 2, contentUrl: "https://youtube.com/watch?v=abc6" },
  { id: "les-3-3", title: "Source Code Project", type: "download", duration: 0, isFree: false, order: 3, contentUrl: "/files/source.zip" },
];

const sampleModules: CourseModule[] = [
  {
    id: "mod-1",
    title: "Dasar React & Next.js",
    description: "Pelajari fundamental React dan pengenalan Next.js 14",
    objectives: ["Memahami JSX", "Mengenal komponen React", "Setup project Next.js"],
    order: 1,
    lessons: mod1Lessons,
  },
  {
    id: "mod-2",
    title: "App Router & Data Fetching",
    description: "Mendalami App Router, Server Components, dan pola data fetching modern",
    objectives: ["Menguasai App Router", "Server vs Client Components", "Streaming & Suspense"],
    order: 2,
    lessons: mod2Lessons,
  },
  {
    id: "mod-3",
    title: "API Routes & Authentication",
    description: "Bangun REST API dan sistem autentikasi untuk aplikasi Anda",
    objectives: ["Membuat API Routes", "Integrasi NextAuth", "Protected routes"],
    order: 3,
    lessons: mod3Lessons,
  },
];

const emptyModules: CourseModule[] = [];
const oneLesson: CourseModule["lessons"] = [
  { id: "les-x-1", title: "Pengenalan UI/UX", type: "video", duration: 600, isFree: true, order: 1, contentUrl: "https://youtube.com/watch?v=ux1" },
];

export const MOCK_COURSES: Course[] = [
  {
    id: "course-001",
    title: "Full Stack Web Development dengan Next.js 14",
    slug: "full-stack-web-development-nextjs-14",
    instructor: {
      id: "inst-001",
      name: "Budi Santoso",
      title: "Senior Web Developer",
      avatar: "/images/instructors/budi.jpg",
    },
    description: "<p>Kursus lengkap belajar Next.js 14 dari nol hingga mahir dengan project nyata.</p>",
    shortDescription: "Pelajari Next.js 14 dari dasar hingga mahir dengan project nyata.",
    whatYouWillLearn: [
      "Memahami konsep App Router",
      "Server Components & Client Components",
      "Data fetching patterns",
      "API Routes & Authentication",
    ],
    targetAudience: [
      "Developer yang familiar dengan React",
      "Pemula yang ingin belajar full-stack",
    ],
    thumbnail: {
      url: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    trailerUrl: "https://youtube.com/watch?v=trailer-nextjs",
    category: "teknologi",
    level: "menengah",
    language: "id",
    tags: ["nextjs", "react", "fullstack", "typescript"],
    price: 350000,
    isFree: false,
    discount: {
      enabled: true,
      originalPrice: 500000,
      percent: 30,
      validUntil: "2026-07-31",
    },
    status: "published",
    featured: true,
    certificateEnabled: true,
    discussionEnabled: true,
    modules: sampleModules,
    studentCount: 234,
    rating: 4.8,
    reviewCount: 56,
    estimatedDuration: 9120,
    publishedAt: daysAgo(30),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(5),
  },
  {
    id: "course-002",
    title: "UI/UX Design Masterclass: Dari Wireframe ke Prototype",
    slug: "uiux-design-masterclass",
    instructor: {
      id: "inst-002",
      name: "Sarah Putri",
      title: "Lead Product Designer",
      avatar: "/images/instructors/sarah.jpg",
    },
    description: "<p>Pelajari UI/UX design dari dasar hingga membuat prototype interaktif dengan Figma.</p>",
    shortDescription: "Kursus UI/UX design komprehensif dengan Figma.",
    whatYouWillLearn: ["Design thinking", "Wireframing", "Prototyping dengan Figma", "Design system"],
    targetAudience: ["Designer pemula", "Developer yang ingin belajar design"],
    thumbnail: {
      url: "https://images.unsplash.com/photo-1561070791-2526d30994b8?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    trailerUrl: "https://youtube.com/watch?v=trailer-uiux",
    category: "desain",
    level: "pemula",
    language: "id",
    tags: ["uiux", "figma", "design"],
    price: 250000,
    isFree: false,
    discount: null,
    status: "published",
    featured: true,
    certificateEnabled: true,
    discussionEnabled: true,
    modules: [
      {
        id: "mod-u1",
        title: "Pengenalan UI/UX",
        description: "Konsep dasar dan tools yang digunakan",
        objectives: ["Memahami UI vs UX", "Mengenal Figma"],
        order: 1,
        lessons: oneLesson,
      },
    ],
    studentCount: 412,
    rating: 4.9,
    reviewCount: 89,
    estimatedDuration: 3600,
    publishedAt: daysAgo(20),
    createdAt: daysAgo(35),
    updatedAt: daysAgo(8),
  },
  {
    id: "course-003",
    title: "Digital Marketing Pro: Strategi & Eksekusi",
    slug: "digital-marketing-pro",
    instructor: {
      id: "inst-003",
      name: "Ahmad Hidayat",
      title: "Digital Marketing Expert",
      avatar: "/images/instructors/ahmad.jpg",
    },
    description: "<p>Strategi digital marketing terkini untuk meningkatkan bisnis Anda.</p>",
    shortDescription: "Kursus digital marketing untuk pemula hingga mahir.",
    whatYouWillLearn: ["SEO", "Social media marketing", "Content marketing", "Email marketing"],
    targetAudience: ["Pemilik bisnis", "Marketing pemula"],
    thumbnail: {
      url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    trailerUrl: "",
    category: "pemasaran",
    level: "pemula",
    language: "id",
    tags: ["marketing", "seo", "social media"],
    price: 0,
    isFree: true,
    discount: null,
    status: "published",
    featured: false,
    certificateEnabled: false,
    discussionEnabled: true,
    modules: emptyModules,
    studentCount: 1024,
    rating: 4.7,
    reviewCount: 156,
    estimatedDuration: 0,
    publishedAt: daysAgo(60),
    createdAt: daysAgo(75),
    updatedAt: daysAgo(10),
  },
  {
    id: "course-004",
    title: "Data Science dengan Python & Machine Learning",
    slug: "data-science-python-ml",
    instructor: {
      id: "inst-004",
      name: "Dr. Lina Marlina",
      title: "Data Scientist",
      avatar: "/images/instructors/lina.jpg",
    },
    description: "<p>Belajar data science dari fundamental hingga machine learning.</p>",
    shortDescription: "Data science end-to-end dengan Python.",
    whatYouWillLearn: ["Python untuk data science", "Pandas & NumPy", "Machine Learning", "Deep Learning basics"],
    targetAudience: ["Mahasiswa", "Developer yang ingin transisi ke AI"],
    thumbnail: {
      url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    trailerUrl: "https://youtube.com/watch?v=trailer-ds",
    category: "data",
    level: "mahir",
    language: "id",
    tags: ["python", "data science", "machine learning"],
    price: 750000,
    isFree: false,
    discount: {
      enabled: true,
      originalPrice: 1000000,
      percent: 25,
      validUntil: "2026-08-15",
    },
    status: "draft",
    featured: false,
    certificateEnabled: true,
    discussionEnabled: true,
    modules: [
      {
        id: "mod-d1",
        title: "Python Fundamentals",
        description: "Dasar-dasar Python untuk data science",
        objectives: ["Syntax Python", "Data types", "Functions"],
        order: 1,
        lessons: [],
      },
    ],
    studentCount: 0,
    rating: 0,
    reviewCount: 0,
    estimatedDuration: 0,
    publishedAt: null,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(0),
  },
  {
    id: "course-005",
    title: "Bisnis Online dari Nol: Build & Scale",
    slug: "bisnis-online-dari-nol",
    instructor: {
      id: "inst-005",
      name: "Reza Pratama",
      title: "Serial Entrepreneur",
      avatar: "/images/instructors/reza.jpg",
    },
    description: "<p>Panduan lengkap membangun bisnis online dari nol.</p>",
    shortDescription: "Langkah praktis membangun bisnis online.",
    whatYouWillLearn: ["Validasi ide bisnis", "MVP", "Marketing & sales", "Scale up"],
    targetAudience: ["Calon entrepreneur", "Pemilik bisnis kecil"],
    thumbnail: {
      url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    trailerUrl: "",
    category: "bisnis",
    level: "pemula",
    language: "id",
    tags: ["entrepreneur", "startup", "business"],
    price: 199000,
    isFree: false,
    discount: null,
    status: "coming_soon",
    featured: true,
    certificateEnabled: true,
    discussionEnabled: true,
    modules: emptyModules,
    studentCount: 0,
    rating: 0,
    reviewCount: 0,
    estimatedDuration: 0,
    publishedAt: null,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },
  {
    id: "course-006",
    title: "Mobile App Development dengan React Native",
    slug: "mobile-app-react-native",
    instructor: {
      id: "inst-001",
      name: "Budi Santoso",
      title: "Senior Web Developer",
      avatar: "/images/instructors/budi.jpg",
    },
    description: "<p>Buat aplikasi mobile cross-platform dengan React Native.</p>",
    shortDescription: "Bangun mobile app iOS & Android dengan satu codebase.",
    whatYouWillLearn: ["React Native basics", "Navigation", "State management", "Publishing ke Play Store"],
    targetAudience: ["React developer", "Pemula mobile dev"],
    thumbnail: {
      url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    trailerUrl: "https://youtube.com/watch?v=trailer-rn",
    category: "teknologi",
    level: "menengah",
    language: "id",
    tags: ["react native", "mobile", "javascript"],
    price: 400000,
    isFree: false,
    discount: null,
    status: "published",
    featured: false,
    certificateEnabled: true,
    discussionEnabled: true,
    modules: [],
    studentCount: 89,
    rating: 4.6,
    reviewCount: 18,
    estimatedDuration: 5400,
    publishedAt: daysAgo(50),
    createdAt: daysAgo(65),
    updatedAt: daysAgo(15),
  },
  {
    id: "course-007",
    title: "Content Creation & Copywriting untuk Bisnis",
    slug: "content-creation-copywriting",
    instructor: {
      id: "inst-006",
      name: "Maya Sari",
      title: "Content Strategist",
      avatar: "/images/instructors/maya.jpg",
    },
    description: "<p>Pelajari seni menulis copy yang menjual dan content creation.</p>",
    shortDescription: "Seni menulis copy yang converting.",
    whatYouWillLearn: ["Copywriting framework", "Storytelling", "Headline writing", "CTA optimization"],
    targetAudience: ["Content creator", "Pemilik bisnis", "Marketer"],
    thumbnail: {
      url: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    trailerUrl: "",
    category: "kreatif",
    level: "pemula",
    language: "id",
    tags: ["copywriting", "content", "writing"],
    price: 150000,
    isFree: false,
    discount: null,
    status: "draft",
    featured: false,
    certificateEnabled: true,
    discussionEnabled: true,
    modules: emptyModules,
    studentCount: 0,
    rating: 0,
    reviewCount: 0,
    estimatedDuration: 0,
    publishedAt: null,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0),
  },
];

export const CATEGORY_FILTER_OPTIONS = [
  { value: "all", label: "Semua Kategori" },
  ...[{ value: "teknologi", label: "Teknologi" }, { value: "bisnis", label: "Bisnis" }, { value: "kreatif", label: "Kreatif" }, { value: "pemasaran", label: "Pemasaran" }, { value: "desain", label: "Desain" }, { value: "data", label: "Data & AI" }],
];

export const LEVEL_FILTER_OPTIONS = [
  { value: "all", label: "Semua Level" },
  { value: "pemula", label: "Pemula" },
  { value: "menengah", label: "Menengah" },
  { value: "mahir", label: "Mahir" },
];
