import type { Article } from "./types";

const AVATAR_ADMIN = "/images/avatar-3.jpeg";

const baseDate = new Date("2026-06-09T10:00:00Z").getTime();
const daysAgo = (n: number) => new Date(baseDate - n * 86400000).toISOString();

export const MOCK_ARTICLES: Article[] = [
  {
    id: "art-001",
    title: "10 Tips Optimasi Performa Website untuk UX yang Lebih Baik",
    slug: "10-tips-optimasi-performa-website",
    excerpt: "Pelajari 10 tips optimasi performa website yang dapat meningkatkan user experience secara signifikan.",
    content: "<p>Performa website adalah faktor krusial yang直接影响用户体验...</p>",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    category: "tips",
    tags: ["performance", "ux", "web"],
    author: { id: "admin-001", name: "Admin CreTechin", avatar: AVATAR_ADMIN },
    status: "published",
    featured: true,
    allowComments: true,
    views: 2450,
    likes: 89,
    comments: 12,
    readTime: 7,
    publishedAt: daysAgo(2),
    scheduledAt: null,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(2),
  },
  {
    id: "art-002",
    title: "Memulai dengan React 19: Panduan Lengkap untuk Pemula",
    slug: "memulai-react-19-panduan-lengkap",
    excerpt: "React 19 membawa banyak fitur baru. Artikel ini membahas semuanya untuk pemula.",
    content: "<p>React 19 adalah rilis terbaru yang membawa banyak perubahan...</p>",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    category: "tutorial",
    tags: ["react", "javascript", "frontend"],
    author: { id: "admin-001", name: "Admin CreTechin", avatar: AVATAR_ADMIN },
    status: "published",
    featured: false,
    allowComments: true,
    views: 1830,
    likes: 64,
    comments: 8,
    readTime: 12,
    publishedAt: daysAgo(8),
    scheduledAt: null,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(8),
  },
  {
    id: "art-003",
    title: "Tren AI Generatif 2026: Dampaknya pada Industri Kreatif",
    slug: "tren-ai-generatif-2026",
    excerpt: "AI generatif mengubah landscape industri kreatif. Simak analisis lengkapnya.",
    content: "<p>AI generatif telah berkembang pesat dalam dua tahun terakhir...</p>",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    category: "berita",
    tags: ["ai", "teknologi", "tren"],
    author: { id: "admin-001", name: "Admin CreTechin", avatar: AVATAR_ADMIN },
    status: "published",
    featured: true,
    allowComments: true,
    views: 3210,
    likes: 142,
    comments: 23,
    readTime: 9,
    publishedAt: daysAgo(5),
    scheduledAt: null,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(5),
  },
  {
    id: "art-004",
    title: "Webinar: Membangun Startup Tech di Era Modern",
    slug: "webinar-membangun-startup-tech",
    excerpt: "Bergabunglah dengan webinar eksklusif kami tentang membangun startup tech.",
    content: "<p>Webinar ini akan membahas strategi membangun startup tech...</p>",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    category: "event",
    tags: ["startup", "webinar", "event"],
    author: { id: "admin-001", name: "Admin CreTechin", avatar: AVATAR_ADMIN },
    status: "draft",
    featured: false,
    allowComments: true,
    views: 0,
    likes: 0,
    comments: 0,
    readTime: 5,
    publishedAt: null,
    scheduledAt: null,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },
  {
    id: "art-005",
    title: "Mengenal TypeScript 5.5: Fitur Baru yang Wajib Dicoba",
    slug: "typescript-55-fitur-baru",
    excerpt: "TypeScript 5.5 membawa banyak fitur baru. Yuk eksplorasi bersama!",
    content: "<p>TypeScript 5.5 telah rilis dengan berbagai improvement...</p>",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    category: "tutorial",
    tags: ["typescript", "javascript", "programming"],
    author: { id: "admin-001", name: "Admin CreTechin", avatar: AVATAR_ADMIN },
    status: "published",
    featured: false,
    allowComments: true,
    views: 1240,
    likes: 45,
    comments: 6,
    readTime: 8,
    publishedAt: daysAgo(12),
    scheduledAt: null,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(12),
  },
  {
    id: "art-006",
    title: "Membangun Komunitas Developer yang Solid",
    slug: "membangun-komunitas-developer",
    excerpt: "Komunitas yang kuat adalah kunci sukses di industri tech.",
    content: "<p>Komunitas developer yang aktif dapat mempercepat pertumbuhan...</p>",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    category: "komunitas",
    tags: ["komunitas", "developer", "networking"],
    author: { id: "admin-001", name: "Admin CreTechin", avatar: AVATAR_ADMIN },
    status: "published",
    featured: false,
    allowComments: true,
    views: 890,
    likes: 32,
    comments: 4,
    readTime: 6,
    publishedAt: daysAgo(20),
    scheduledAt: null,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(20),
  },
  {
    id: "art-007",
    title: "Insight: Peluang Karir UI/UX Designer di Indonesia 2026",
    slug: "peluang-karir-uiux-2026",
    excerpt: "Industri UI/UX di Indonesia terus bertumbuh. Peluang karir menanti Anda.",
    content: "<p>Permintaan akan UI/UX designer terus meningkat...</p>",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1561070791-2526d30994b8?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    category: "insight",
    tags: ["uiux", "karir", "industri"],
    author: { id: "admin-001", name: "Admin CreTechin", avatar: AVATAR_ADMIN },
    status: "draft",
    featured: false,
    allowComments: true,
    views: 0,
    likes: 0,
    comments: 0,
    readTime: 10,
    publishedAt: null,
    scheduledAt: null,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(0),
  },
  {
    id: "art-008",
    title: "Cara Efektif Belajar Programming untuk Pemula",
    slug: "cara-efektif-belajar-programming",
    excerpt: "Panduan lengkap belajar programming dari nol untuk pemula.",
    content: "<p>Belajar programming memang menantang, tapi dengan strategi yang tepat...</p>",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    category: "tips",
    tags: ["programming", "pemula", "belajar"],
    author: { id: "admin-001", name: "Admin CreTechin", avatar: AVATAR_ADMIN },
    status: "published",
    featured: true,
    allowComments: true,
    views: 4520,
    likes: 198,
    comments: 34,
    readTime: 11,
    publishedAt: daysAgo(30),
    scheduledAt: null,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(30),
  },
  {
    id: "art-009",
    title: "Roadmap Web Developer 2026: From Zero to Hero",
    slug: "roadmap-web-developer-2026",
    excerpt: "Roadmap lengkap menjadi web developer profesional di tahun 2026.",
    content: "<p>Menjadi web developer yang handal membutuhkan roadmap yang jelas...</p>",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1547658719-da2b51169166?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    category: "tutorial",
    tags: ["web developer", "roadmap", "karir"],
    author: { id: "admin-001", name: "Admin CreTechin", avatar: AVATAR_ADMIN },
    status: "published",
    featured: false,
    allowComments: true,
    views: 2890,
    likes: 112,
    comments: 18,
    readTime: 14,
    publishedAt: daysAgo(45),
    scheduledAt: null,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(45),
  },
  {
    id: "art-010",
    title: "Next.js 15 vs Remix: Mana yang Lebih Unggul?",
    slug: "nextjs-15-vs-remix",
    excerpt: "Perbandingan mendalam antara Next.js 15 dan Remix untuk project modern.",
    content: "<p>Kedua framework ini memiliki kelebihan masing-masing...</p>",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    category: "insight",
    tags: ["nextjs", "remix", "framework"],
    author: { id: "admin-001", name: "Admin CreTechin", avatar: AVATAR_ADMIN },
    status: "draft",
    featured: false,
    allowComments: true,
    views: 0,
    likes: 0,
    comments: 0,
    readTime: 13,
    publishedAt: null,
    scheduledAt: null,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0),
  },
  {
    id: "art-011",
    title: "Hackathon CreTechin 2026: Daftar Sekarang!",
    slug: "hackathon-cretechin-2026",
    excerpt: "Hackathon terbesar tahun ini dengan hadiah jutaan rupiah.",
    content: "<p>Hackathon CreTechin 2026 akan segera digelar...</p>",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    category: "event",
    tags: ["hackathon", "event", "kompetisi"],
    author: { id: "admin-001", name: "Admin CreTechin", avatar: AVATAR_ADMIN },
    status: "scheduled",
    featured: true,
    allowComments: true,
    views: 0,
    likes: 0,
    comments: 0,
    readTime: 4,
    publishedAt: null,
    scheduledAt: daysAgo(-7),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },
  {
    id: "art-012",
    title: "Tips Produktivitas untuk Developer: Work Smart, Not Hard",
    slug: "tips-produktivitas-developer",
    excerpt: "Tingkatkan produktivitas Anda sebagai developer dengan tips berikut.",
    content: "<p>Menjadi developer yang produktif membutuhkan strategi...</p>",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=400&h=400&fit=crop",
      width: 400,
      height: 400,
    },
    category: "tips",
    tags: ["produktivitas", "developer", "tips"],
    author: { id: "admin-001", name: "Admin CreTechin", avatar: AVATAR_ADMIN },
    status: "published",
    featured: false,
    allowComments: true,
    views: 1560,
    likes: 78,
    comments: 9,
    readTime: 7,
    publishedAt: daysAgo(60),
    scheduledAt: null,
    createdAt: daysAgo(65),
    updatedAt: daysAgo(60),
  },
];

export const CATEGORY_FILTER_OPTIONS = [
  { value: "all", label: "Semua Kategori" },
  { value: "tips", label: "Tips & Trik" },
  { value: "tutorial", label: "Tutorial" },
  { value: "berita", label: "Berita Teknologi" },
  { value: "event", label: "Event & Webinar" },
  { value: "insight", label: "Insight Industri" },
  { value: "komunitas", label: "Komunitas" },
];
