import type { Event } from "./types";

export const MOCK_EVENTS: Event[] = [
  // 4 Upcoming
  {
    id: "evt-001",
    slug: "tren-ai-2026",
    title: "Tren AI 2026: Peluang & Tantangan",
    shortDescription:
      "Membahas perkembangan AI generatif terbaru dan dampaknya terhadap industri kreatif di Indonesia.",
    description:
      "Webinar ini akan membahas tren AI 2026 secara mendalam, mulai dari generative AI, multimodal models, hingga dampaknya terhadap workflow desainer dan developer di Indonesia. Peserta akan mendapat insight praktis dari praktisi AI lokal.",
    type: "webinar",
    status: "upcoming",
    startDate: "2026-06-15T12:00:00Z",
    endDate: "2026-06-15T14:00:00Z",
    timezone: "WIB",
    location: {
      type: "online",
      platform: "zoom",
      meetingUrl: "https://zoom.us/j/1234567890",
      meetingId: "123 456 7890",
      passcode: "cretechin2026",
    },
    speakers: [
      {
        id: "spk-001",
        name: "Andi Wijaya",
        title: "AI Researcher & Tech Lead",
        bio: "Peneliti AI dengan 10+ tahun pengalaman di bidang NLP dan computer vision.",
        order: 0,
        avatar: {
          url: "https://i.pravatar.cc/150?img=11",
          width: 150,
          height: 150,
        },
        linkedinUrl: "https://linkedin.com/in/example",
      },
    ],
    topics: [
      "Generative AI di industri kreatif",
      "Multimodal models",
      "Etika AI & regulasi",
      "Implementasi praktis untuk startup",
    ],
    price: 0,
    isFree: true,
    earlyBird: null,
    capacity: 200,
    registeredCount: 120,
    banner: {
      url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1280&h=720&fit=crop",
      width: 1280,
      height: 720,
    },
    featured: true,
    allowRegistration: true,
    sendReminder: true,
    recordEvent: true,
    autoCloseRegistration: true,
    viewCount: 1842,
    attendanceRate: 0,
    rating: 0,
    reviewCount: 0,
    createdAt: "2026-05-10T08:00:00Z",
    updatedAt: "2026-06-05T10:00:00Z",
    publishedAt: "2026-05-12T08:00:00Z",
  },
  {
    id: "evt-002",
    slug: "figma-workshop-advanced",
    title: "Figma Workshop: Advanced Components",
    shortDescription:
      "Hands-on workshop membangun design system dan component library yang scalable di Figma.",
    description:
      "Workshop intensif 4 jam untuk designer yang ingin menguasai Figma di level advanced. Materi meliputi auto-layout, variants, component properties, dan best practices design system.",
    type: "workshop",
    status: "upcoming",
    startDate: "2026-06-20T06:00:00Z",
    endDate: "2026-06-20T10:00:00Z",
    timezone: "WIB",
    location: {
      type: "online",
      platform: "google_meet",
      meetingUrl: "https://meet.google.com/abc-defg-hij",
      meetingId: "abc-defg-hij",
    },
    speakers: [
      {
        id: "spk-002",
        name: "Sarah Lin",
        title: "Senior Product Designer",
        bio: "Product designer dengan pengalaman 8 tahun di startup unicorn Asia Tenggara.",
        order: 0,
        avatar: {
          url: "https://i.pravatar.cc/150?img=5",
          width: 150,
          height: 150,
        },
      },
    ],
    topics: [
      "Auto-layout mastery",
      "Component variants & properties",
      "Design tokens",
      "Handoff ke developer",
    ],
    price: 150000,
    isFree: false,
    earlyBird: {
      enabled: true,
      price: 99000,
      validUntil: "2026-06-17T23:59:00Z",
    },
    capacity: 50,
    registeredCount: 48,
    banner: {
      url: "https://images.unsplash.com/photo-1559028012-481c04fa702d?w=1280&h=720&fit=crop",
      width: 1280,
      height: 720,
    },
    featured: true,
    allowRegistration: true,
    sendReminder: true,
    recordEvent: true,
    autoCloseRegistration: true,
    viewCount: 956,
    attendanceRate: 0,
    rating: 0,
    reviewCount: 0,
    createdAt: "2026-05-15T08:00:00Z",
    updatedAt: "2026-06-08T10:00:00Z",
    publishedAt: "2026-05-16T08:00:00Z",
  },
  {
    id: "evt-003",
    slug: "startup-talkshow-funding",
    title: "Talkshow: Pendanaan Startup di Indonesia",
    shortDescription:
      "Bedah strategi fundraising dengan VC dan founder startup sukses Indonesia.",
    description:
      "Sesi talkshow interaktif membahas landscape pendanaan startup di Indonesia, tips pitching ke investor, dan pengalaman founder sukses dalam journey mereka.",
    type: "talkshow",
    status: "upcoming",
    startDate: "2026-07-05T12:00:00Z",
    endDate: "2026-07-05T14:30:00Z",
    timezone: "WIB",
    location: {
      type: "online",
      platform: "zoom",
      meetingUrl: "https://zoom.us/j/9876543210",
    },
    speakers: [
      {
        id: "spk-003",
        name: "Budi Hartono",
        title: "Managing Partner, East Ventures",
        order: 0,
        avatar: {
          url: "https://i.pravatar.cc/150?img=12",
          width: 150,
          height: 150,
        },
      },
      {
        id: "spk-004",
        name: "Rina Kusuma",
        title: "Founder & CEO, TechStartup ID",
        order: 1,
        avatar: {
          url: "https://i.pravatar.cc/150?img=9",
          width: 150,
          height: 150,
        },
      },
    ],
    topics: ["Pre-seed vs Seed", "Pitch deck terbaik", "Due diligence VC"],
    price: 50000,
    isFree: false,
    earlyBird: null,
    capacity: 300,
    registeredCount: 87,
    banner: {
      url: "https://images.unsplash.com/photo-1559223607-a43c990c692c?w=1280&h=720&fit=crop",
      width: 1280,
      height: 720,
    },
    featured: false,
    allowRegistration: true,
    sendReminder: true,
    recordEvent: false,
    autoCloseRegistration: true,
    viewCount: 423,
    attendanceRate: 0,
    rating: 0,
    reviewCount: 0,
    createdAt: "2026-05-20T08:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
    publishedAt: "2026-05-22T08:00:00Z",
  },
  {
    id: "evt-004",
    slug: "design-conference-2026",
    title: "Indonesia Design Conference 2026",
    shortDescription:
      "Konferensi desain terbesar di Indonesia dengan 30+ pembicara internasional.",
    description:
      "Tiga hari penuh dengan talks, workshops, dan networking session bersama designer-d designer terbaik Indonesia dan Asia Tenggara.",
    type: "conference",
    status: "upcoming",
    startDate: "2026-08-10T01:00:00Z",
    endDate: "2026-08-12T10:00:00Z",
    timezone: "WIB",
    location: {
      type: "offline",
      venueName: "JCC Plenary Hall",
      address: "Jl. Gatot Subroto Kav. 47, Jakarta Selatan",
      city: "Jakarta",
      mapsUrl: "https://maps.google.com/?q=JCC+Plenary+Hall",
    },
    speakers: [
      {
        id: "spk-005",
        name: "Ridwan Kamil",
        title: "Designer & Former Governor",
        order: 0,
      },
    ],
    topics: [
      "Design systems at scale",
      "Service design",
      "Inclusive design",
      "Design ops",
    ],
    price: 2500000,
    isFree: false,
    earlyBird: {
      enabled: true,
      price: 1500000,
      validUntil: "2026-06-30T23:59:00Z",
    },
    capacity: 500,
    registeredCount: 234,
    banner: {
      url: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1280&h=720&fit=crop",
      width: 1280,
      height: 720,
    },
    featured: true,
    allowRegistration: true,
    sendReminder: true,
    recordEvent: false,
    autoCloseRegistration: false,
    viewCount: 2341,
    attendanceRate: 0,
    rating: 0,
    reviewCount: 0,
    createdAt: "2026-04-15T08:00:00Z",
    updatedAt: "2026-06-08T10:00:00Z",
    publishedAt: "2026-04-20T08:00:00Z",
  },

  // 1 Ongoing (startDate <= NOW <= endDate)
  {
    id: "evt-005",
    slug: "live-coding-react",
    title: "Live Coding: Building React App",
    shortDescription:
      "Sesi live coding membangun aplikasi React dari nol hingga deploy.",
    description:
      "Tonton dan belajar langsung dari senior developer membangun aplikasi React production-ready, lengkap dengan best practices, error handling, dan optimasi performance.",
    type: "workshop",
    status: "ongoing",
    startDate: "2026-06-09T08:00:00Z",
    endDate: "2026-06-09T12:00:00Z",
    timezone: "WIB",
    location: {
      type: "online",
      platform: "teams",
      meetingUrl: "https://teams.microsoft.com/l/meetup-join/abc",
    },
    speakers: [
      {
        id: "spk-006",
        name: "Dimas Prasetyo",
        title: "Senior Frontend Engineer",
        order: 0,
        avatar: {
          url: "https://i.pravatar.cc/150?img=15",
          width: 150,
          height: 150,
        },
      },
    ],
    topics: [
      "Project setup dengan Vite",
      "Component architecture",
      "State management",
      "Deployment ke Vercel",
    ],
    price: 75000,
    isFree: false,
    earlyBird: null,
    capacity: 100,
    registeredCount: 85,
    banner: {
      url: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1280&h=720&fit=crop",
      width: 1280,
      height: 720,
    },
    featured: false,
    allowRegistration: false,
    sendReminder: true,
    recordEvent: true,
    autoCloseRegistration: true,
    viewCount: 1245,
    attendanceRate: 0,
    rating: 0,
    reviewCount: 0,
    createdAt: "2026-05-25T08:00:00Z",
    updatedAt: "2026-06-09T08:00:00Z",
    publishedAt: "2026-05-26T08:00:00Z",
  },

  // 2 Finished
  {
    id: "evt-006",
    slug: "webinar-future-of-web",
    title: "Future of Web Development",
    shortDescription:
      "Webinar tentang masa depan web development: dari WebAssembly hingga edge computing.",
    description:
      "Membahas trend web development ke depan, termasuk WebAssembly, edge computing, dan framework terbaru yang akan mendominasi industri.",
    type: "webinar",
    status: "finished",
    startDate: "2026-05-15T12:00:00Z",
    endDate: "2026-05-15T14:00:00Z",
    timezone: "WIB",
    location: {
      type: "online",
      platform: "zoom",
      meetingUrl: "https://zoom.us/j/111222333",
    },
    speakers: [
      {
        id: "spk-007",
        name: "Kevin Tan",
        title: "Web Platform Lead",
        order: 0,
      },
    ],
    topics: ["WebAssembly", "Edge computing", "Jamstack evolution"],
    price: 0,
    isFree: true,
    earlyBird: null,
    capacity: 200,
    registeredCount: 156,
    banner: {
      url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1280&h=720&fit=crop",
      width: 1280,
      height: 720,
    },
    featured: false,
    allowRegistration: true,
    sendReminder: true,
    recordEvent: true,
    autoCloseRegistration: true,
    viewCount: 3142,
    attendanceRate: 78,
    rating: 4.7,
    reviewCount: 89,
    createdAt: "2026-04-20T08:00:00Z",
    updatedAt: "2026-05-15T15:00:00Z",
    publishedAt: "2026-04-25T08:00:00Z",
  },
  {
    id: "evt-007",
    slug: "meetup-developer-jakarta",
    title: "Developer Meetup Jakarta",
    shortDescription:
      "Meetup bulanan komunitas developer Jakarta dengan tema microservices.",
    description:
      "Sesi networking dan sharing knowledge antar developer di Jakarta. Bulan ini bertema microservices architecture dan best practices-nya.",
    type: "meetup",
    status: "finished",
    startDate: "2026-05-25T11:00:00Z",
    endDate: "2026-05-25T14:00:00Z",
    timezone: "WIB",
    location: {
      type: "offline",
      venueName: "Co&Work Co-working Space",
      address: "Jl. Kemang Raya No. 17, Jakarta Selatan",
      city: "Jakarta",
      mapsUrl: "https://maps.google.com/?q=Kemang+Jakarta",
    },
    speakers: [
      {
        id: "spk-008",
        name: "Rio Wibowo",
        title: "Backend Engineer",
        order: 0,
      },
    ],
    topics: ["Microservices", "API Gateway", "Service mesh"],
    price: 25000,
    isFree: false,
    earlyBird: null,
    capacity: 80,
    registeredCount: 80,
    banner: {
      url: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=1280&h=720&fit=crop",
      width: 1280,
      height: 720,
    },
    featured: false,
    allowRegistration: true,
    sendReminder: true,
    recordEvent: false,
    autoCloseRegistration: true,
    viewCount: 567,
    attendanceRate: 85,
    rating: 4.5,
    reviewCount: 34,
    createdAt: "2026-04-25T08:00:00Z",
    updatedAt: "2026-05-25T15:00:00Z",
    publishedAt: "2026-04-28T08:00:00Z",
  },

  // 2 Draft
  {
    id: "evt-008",
    slug: "networking-creator",
    title: "Networking Night: Content Creators",
    shortDescription:
      "Malam networking khusus content creator Indonesia untuk kolaborasi dan sharing insights.",
    description:
      "Acara networking casual untuk content creator, YouTuber, streamer, dan kreator konten di Indonesia.",
    type: "networking",
    status: "draft",
    startDate: "2026-07-20T12:00:00Z",
    endDate: "2026-07-20T15:00:00Z",
    timezone: "WIB",
    location: {
      type: "offline",
      venueName: "TBA",
      address: "Akan diumumkan",
      city: "Jakarta",
    },
    speakers: [],
    topics: ["Content collaboration", "Brand deals", "Audience growth"],
    price: 100000,
    isFree: false,
    earlyBird: null,
    capacity: 60,
    registeredCount: 0,
    banner: null,
    featured: false,
    allowRegistration: true,
    sendReminder: true,
    recordEvent: false,
    autoCloseRegistration: true,
    viewCount: 0,
    attendanceRate: 0,
    rating: 0,
    reviewCount: 0,
    createdAt: "2026-06-01T08:00:00Z",
    updatedAt: "2026-06-08T10:00:00Z",
    publishedAt: null,
  },
  {
    id: "evt-009",
    slug: "talkshow-cybersecurity",
    title: "Talkshow: Cybersecurity untuk UMKM",
    shortDescription:
      "Edisi khusus membahas keamanan siber untuk pelaku UMKM di Indonesia.",
    description:
      "Talkshow edukatif tentang pentingnya cybersecurity untuk UMKM, dengan studi kasus dan tips praktis dari praktisi keamanan siber.",
    type: "talkshow",
    status: "draft",
    startDate: "2026-08-01T12:00:00Z",
    endDate: "2026-08-01T14:00:00Z",
    timezone: "WIB",
    location: {
      type: "online",
      platform: "zoom",
    },
    speakers: [],
    topics: ["Phishing awareness", "Data protection", "Incident response"],
    price: 0,
    isFree: true,
    earlyBird: null,
    capacity: 150,
    registeredCount: 0,
    banner: null,
    featured: false,
    allowRegistration: true,
    sendReminder: true,
    recordEvent: true,
    autoCloseRegistration: true,
    viewCount: 0,
    attendanceRate: 0,
    rating: 0,
    reviewCount: 0,
    createdAt: "2026-06-05T08:00:00Z",
    updatedAt: "2026-06-08T10:00:00Z",
    publishedAt: null,
  },

  // 1 Offline Upcoming
  {
    id: "evt-010",
    slug: "offline-workshop-design-system",
    title: "Workshop Offline: Building Design System",
    shortDescription:
      "Workshop offline intensif membangun design system dari nol.",
    description:
      "Workshop offline 6 jam yang akan memandu Anda membangun design system lengkap untuk perusahaan Anda, dari token hingga component library.",
    type: "workshop",
    status: "upcoming",
    startDate: "2026-07-15T03:00:00Z",
    endDate: "2026-07-15T09:00:00Z",
    timezone: "WIB",
    location: {
      type: "offline",
      venueName: "CreTechin Hub Jakarta",
      address: "Jl. Sudirman Kav. 1, Jakarta Pusat",
      city: "Jakarta",
      mapsUrl: "https://maps.google.com/?q=CreTechin+Hub",
    },
    speakers: [
      {
        id: "spk-009",
        name: "Maya Sari",
        title: "Design Systems Lead",
        order: 0,
        avatar: {
          url: "https://i.pravatar.cc/150?img=10",
          width: 150,
          height: 150,
        },
      },
    ],
    topics: [
      "Design tokens",
      "Component architecture",
      "Documentation strategy",
      "Adoption & governance",
    ],
    price: 500000,
    isFree: false,
    earlyBird: {
      enabled: true,
      price: 350000,
      validUntil: "2026-07-01T23:59:00Z",
    },
    capacity: 30,
    registeredCount: 12,
    banner: {
      url: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1280&h=720&fit=crop",
      width: 1280,
      height: 720,
    },
    featured: false,
    allowRegistration: true,
    sendReminder: true,
    recordEvent: false,
    autoCloseRegistration: true,
    viewCount: 234,
    attendanceRate: 0,
    rating: 0,
    reviewCount: 0,
    createdAt: "2026-05-30T08:00:00Z",
    updatedAt: "2026-06-08T10:00:00Z",
    publishedAt: "2026-06-01T08:00:00Z",
  },
];
