import type { Product } from "./types";

const NOW_ISO = "2026-06-09T10:00:00Z";
const daysAgo = (d: number) => new Date(new Date(NOW_ISO).getTime() - d * 24 * 60 * 60 * 1000).toISOString();

const thumb = (seed: string, w = 800, h = 600) => ({
  url: `https://picsum.photos/seed/${seed}/${w}/${h}`,
  width: w,
  height: h,
});

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-001",
    slug: "modern-dashboard-ui-kit",
    title: "Modern Dashboard UI Kit",
    description:
      "UI Kit dashboard modern dengan 100+ layar siap pakai untuk aplikasi web dan mobile. Dibangun dengan design system yang konsisten, mendukung light & dark mode, dan mengikuti best practice Material Design 3.",
    shortDescription: "UI Kit dashboard modern dengan 100+ layar siap pakai, light & dark mode, Figma & Sketch.",
    productType: "digital",
    category: "ui_kits",
    status: "published",
    creator: { id: "cr-001", name: "PixelCraft Studio", title: "Design Agency", studioName: "PixelCraft" },
    price: 149000,
    isFree: false,
    discount: { enabled: true, originalPrice: 249000, percent: 40, validUntil: "2026-07-31" },
    stock: 999,
    sku: "UI-PX-001",
    weight: 0,
    thumbnail: { id: "img-001", isPrimary: true, alt: "Modern Dashboard UI Kit", ...thumb("ui-001", 800, 600) },
    gallery: [
      { id: "img-001a", isPrimary: true, alt: "Dashboard overview", ...thumb("ui-001a", 1280, 720) },
      { id: "img-001b", isPrimary: false, alt: "Mobile view", ...thumb("ui-001b", 1280, 720) },
      { id: "img-001c", isPrimary: false, alt: "Component library", ...thumb("ui-001c", 1280, 720) },
    ],
    sourceFile: { name: "modern-dashboard-ui-kit.zip", size: 256 * 1024 * 1024, url: "/files/modern-dashboard-ui-kit.zip" },
    tags: ["dashboard", "figma", "sketch", "admin"],
    specifications: ["100+ Screens", "Light & Dark Mode", "Figma & Sketch", "Material Design 3", "Fully Responsive"],
    whatsIncluded: ["File .fig (Figma)", "File .sketch (Sketch)", "PDF dokumentasi", "Free update 1 tahun"],
    featured: true,
    enableReview: true,
    downloadLimit: 5,
    metaTitle: "Modern Dashboard UI Kit - 100+ Layar Figma Siap Pakai",
    metaDescription: "UI Kit dashboard modern dengan 100+ layar, light & dark mode, Material Design 3. Cocok untuk SaaS, startup, dan enterprise.",
    viewCount: 1240,
    soldCount: 89,
    rating: 4.8,
    reviewCount: 56,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(3),
    publishedAt: daysAgo(40),
  },
  {
    id: "prod-002",
    slug: "ecommerce-mobile-ui-kit",
    title: "E-Commerce Mobile UI Kit",
    description:
      "UI Kit mobile untuk aplikasi e-commerce dengan 80+ layar. Sudah termasuk halaman produk, cart, checkout, profile, dan banyak lagi. Dilengkapi dengan icon set gratis dan 200+ ilustrasi.",
    shortDescription: "UI Kit mobile e-commerce 80+ layar lengkap dengan checkout flow dan 200+ ilustrasi.",
    productType: "digital",
    category: "ui_kits",
    status: "published",
    creator: { id: "cr-002", name: "Budi Santoso", title: "UI/UX Designer" },
    price: 99000,
    isFree: false,
    discount: null,
    stock: 999,
    sku: "UI-BS-002",
    weight: 0,
    thumbnail: { id: "img-002", isPrimary: true, alt: "E-Commerce Mobile UI Kit", ...thumb("ui-002", 800, 600) },
    gallery: [
      { id: "img-002a", isPrimary: true, alt: "Product list", ...thumb("ui-002a", 1280, 720) },
      { id: "img-002b", isPrimary: false, alt: "Checkout flow", ...thumb("ui-002b", 1280, 720) },
    ],
    sourceFile: { name: "ecommerce-mobile-ui-kit.zip", size: 180 * 1024 * 1024, url: "/files/ecommerce-mobile-ui-kit.zip" },
    tags: ["mobile", "ecommerce", "ios", "android"],
    specifications: ["80+ Screens", "iOS & Android", "200+ Ilustrasi", "Icon Set 500+", "Color Tokens"],
    whatsIncluded: ["File .fig (Figma)", "Icon set SVG", "File ilustrasi AI", "Free update 6 bulan"],
    featured: true,
    enableReview: true,
    downloadLimit: 3,
    metaTitle: "E-Commerce Mobile UI Kit - 80+ Layar Figma",
    metaDescription: "UI Kit e-commerce mobile lengkap untuk iOS & Android. 80+ layar siap pakai, 200+ ilustrasi.",
    viewCount: 890,
    soldCount: 124,
    rating: 4.9,
    reviewCount: 78,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(7),
    publishedAt: daysAgo(28),
  },
  {
    id: "prod-003",
    slug: "crypto-wallet-ui-pack",
    title: "Crypto Wallet UI Pack",
    description: "UI Pack untuk aplikasi crypto wallet dengan fokus pada portfolio tracking, swap, dan staking. Dark mode by default dengan neon accent.",
    shortDescription: "UI Pack crypto wallet dengan portfolio tracker, swap, dan staking interface.",
    productType: "digital",
    category: "ui_kits",
    status: "draft",
    creator: { id: "cr-003", name: "CryptoDesign Lab", studioName: "CryptoDesign Lab" },
    price: 199000,
    isFree: false,
    discount: null,
    stock: 999,
    sku: "UI-CD-003",
    weight: 0,
    thumbnail: { id: "img-003", isPrimary: true, alt: "Crypto Wallet UI Pack", ...thumb("ui-003", 800, 600) },
    gallery: [
      { id: "img-003a", isPrimary: true, alt: "Portfolio view", ...thumb("ui-003a", 1280, 720) },
    ],
    tags: ["crypto", "wallet", "web3", "blockchain"],
    specifications: ["50+ Screens", "Dark Mode Neon", "Portfolio Dashboard", "Swap Interface"],
    whatsIncluded: ["File .fig (Figma)", "PDF dokumentasi"],
    featured: false,
    enableReview: true,
    downloadLimit: 5,
    metaTitle: "Crypto Wallet UI Pack - 50+ Layar Web3",
    metaDescription: "UI Pack crypto wallet dengan 50+ layar untuk portfolio, swap, dan staking.",
    viewCount: 0,
    soldCount: 0,
    rating: 0,
    reviewCount: 0,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
    publishedAt: null,
  },
  {
    id: "prod-004",
    slug: "saas-landing-bundle",
    title: "SaaS Landing Bundle",
    description: "Bundle lengkap landing page untuk produk SaaS: 5 template homepage, 3 pricing page, 2 about page, dan komponen-komponen marketing.",
    shortDescription: "Bundle 10+ halaman landing page SaaS dengan komponen marketing siap pakai.",
    productType: "digital",
    category: "templates",
    status: "published",
    creator: { id: "cr-001", name: "PixelCraft Studio", title: "Design Agency", studioName: "PixelCraft" },
    price: 75000,
    isFree: false,
    discount: null,
    stock: 999,
    sku: "TP-PX-004",
    weight: 0,
    thumbnail: { id: "img-004", isPrimary: true, alt: "SaaS Landing Bundle", ...thumb("ui-004", 800, 600) },
    gallery: [
      { id: "img-004a", isPrimary: true, alt: "Homepage", ...thumb("ui-004a", 1280, 720) },
      { id: "img-004b", isPrimary: false, alt: "Pricing page", ...thumb("ui-004b", 1280, 720) },
    ],
    sourceFile: { name: "saas-landing-bundle.zip", size: 45 * 1024 * 1024, url: "/files/saas-landing-bundle.zip" },
    tags: ["saas", "landing-page", "startup", "marketing"],
    specifications: ["10+ Pages", "Next.js + Tailwind", "SEO Optimized", "Responsive", "Dark Mode"],
    whatsIncluded: ["Next.js project", "Tailwind config", "All assets", "Documentation"],
    featured: false,
    enableReview: true,
    downloadLimit: undefined,
    metaTitle: "SaaS Landing Bundle - 10+ Halaman Next.js + Tailwind",
    metaDescription: "Bundle landing page SaaS dengan 10+ halaman siap pakai untuk produk startup Anda.",
    viewCount: 567,
    soldCount: 64,
    rating: 4.7,
    reviewCount: 38,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(10),
    publishedAt: daysAgo(55),
  },
  {
    id: "prod-005",
    slug: "nextjs-starter-template",
    title: "Next.js 14 Starter Template",
    description: "Starter template Next.js 14 dengan App Router, TypeScript, Tailwind, Prisma, NextAuth. Setup lengkap untuk SaaS modern.",
    shortDescription: "Starter Next.js 14 + TypeScript + Prisma + NextAuth untuk SaaS modern.",
    productType: "digital",
    category: "templates",
    status: "published",
    creator: { id: "cr-004", name: "Andi Wijaya", title: "Full Stack Developer" },
    price: 199000,
    isFree: false,
    discount: { enabled: true, originalPrice: 299000, percent: 33, validUntil: "2026-08-15" },
    stock: 999,
    sku: "TP-AW-005",
    weight: 0,
    thumbnail: { id: "img-005", isPrimary: true, alt: "Next.js Starter", ...thumb("ui-005", 800, 600) },
    gallery: [
      { id: "img-005a", isPrimary: true, alt: "Dashboard", ...thumb("ui-005a", 1280, 720) },
      { id: "img-005b", isPrimary: false, alt: "Code structure", ...thumb("ui-005b", 1280, 720) },
      { id: "img-005c", isPrimary: false, alt: "Auth flow", ...thumb("ui-005c", 1280, 720) },
    ],
    sourceFile: { name: "nextjs-starter.zip", size: 8 * 1024 * 1024, url: "/files/nextjs-starter.zip" },
    demoUrl: "https://demo.cretechin.com/nextjs-starter",
    tags: ["nextjs", "typescript", "prisma", "saas"],
    specifications: ["Next.js 14", "TypeScript", "Prisma ORM", "NextAuth", "Tailwind CSS", "Stripe Integration"],
    whatsIncluded: ["Full source code", "Setup documentation", "Video walkthrough", "Discord support"],
    featured: true,
    enableReview: true,
    downloadLimit: undefined,
    metaTitle: "Next.js 14 Starter Template - SaaS Ready",
    metaDescription: "Starter template Next.js 14 dengan TypeScript, Prisma, NextAuth. Siap pakai untuk SaaS modern.",
    viewCount: 2340,
    soldCount: 187,
    rating: 4.9,
    reviewCount: 112,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(5),
    publishedAt: daysAgo(85),
  },
  {
    id: "prod-006",
    slug: "react-admin-dashboard",
    title: "React Admin Dashboard",
    description: "Template admin dashboard dengan React 18, Vite, dan shadcn/ui. 30+ halaman siap pakai dengan dark mode.",
    shortDescription: "Template admin React 18 + Vite + shadcn/ui dengan 30+ halaman.",
    productType: "digital",
    category: "templates",
    status: "draft",
    creator: { id: "cr-005", name: "CodeMaster ID", title: "Dev Studio", studioName: "CodeMaster" },
    price: 129000,
    isFree: false,
    discount: null,
    stock: 999,
    sku: "TP-CM-006",
    weight: 0,
    thumbnail: { id: "img-006", isPrimary: true, alt: "React Admin", ...thumb("ui-006", 800, 600) },
    gallery: [
      { id: "img-006a", isPrimary: true, alt: "Overview", ...thumb("ui-006a", 1280, 720) },
    ],
    tags: ["react", "admin", "dashboard", "shadcn"],
    specifications: ["React 18", "Vite", "shadcn/ui", "30+ Pages", "Dark Mode"],
    whatsIncluded: ["Full source code", "Documentation"],
    featured: false,
    enableReview: true,
    downloadLimit: undefined,
    metaTitle: "React Admin Dashboard Template",
    metaDescription: "Template admin dashboard React 18 + Vite + shadcn/ui.",
    viewCount: 0,
    soldCount: 0,
    rating: 0,
    reviewCount: 0,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    publishedAt: null,
  },
  {
    id: "prod-007",
    slug: "portfolio-html-template",
    title: "Portfolio HTML Template",
    description: "Template portfolio statis untuk developer dan designer. HTML + Tailwind + sedikit JS. Ringan, cepat, SEO-friendly.",
    shortDescription: "Template portfolio statis HTML + Tailwind untuk developer & designer.",
    productType: "digital",
    category: "templates",
    status: "published",
    creator: { id: "cr-002", name: "Budi Santoso", title: "UI/UX Designer" },
    price: 0,
    isFree: true,
    discount: null,
    stock: 999,
    sku: "TP-BS-007",
    weight: 0,
    thumbnail: { id: "img-007", isPrimary: true, alt: "Portfolio HTML", ...thumb("ui-007", 800, 600) },
    gallery: [
      { id: "img-007a", isPrimary: true, alt: "Homepage", ...thumb("ui-007a", 1280, 720) },
    ],
    sourceFile: { name: "portfolio-template.zip", size: 2 * 1024 * 1024, url: "/files/portfolio-template.zip" },
    demoUrl: "https://demo.cretechin.com/portfolio",
    tags: ["portfolio", "html", "tailwind", "free"],
    specifications: ["HTML + Tailwind", "Responsive", "SEO Ready", "Lightweight < 50KB"],
    whatsIncluded: ["HTML files", "CSS", "JS", "Documentation"],
    featured: false,
    enableReview: true,
    downloadLimit: undefined,
    metaTitle: "Portfolio HTML Template Gratis",
    metaDescription: "Template portfolio HTML + Tailwind gratis untuk developer & designer.",
    viewCount: 4520,
    soldCount: 342,
    rating: 4.6,
    reviewCount: 198,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(20),
    publishedAt: daysAgo(118),
  },
  {
    id: "prod-008",
    slug: "iphone-15-pro-mockup",
    title: "iPhone 15 Pro Mockup Pack",
    description: "Mockup iPhone 15 Pro dalam 12 angle berbeda. Format PSD dengan smart object. Resolusi 4000x6000px.",
    shortDescription: "Mockup iPhone 15 Pro 12 angle, PSD smart object, 4000x6000px.",
    productType: "digital",
    category: "mockups",
    status: "published",
    creator: { id: "cr-006", name: "Mockup Studio", title: "Mockup Specialist" },
    price: 49000,
    isFree: false,
    discount: null,
    stock: 999,
    sku: "MK-MS-008",
    weight: 0,
    thumbnail: { id: "img-008", isPrimary: true, alt: "iPhone Mockup", ...thumb("ui-008", 800, 600) },
    gallery: [
      { id: "img-008a", isPrimary: true, alt: "Front view", ...thumb("ui-008a", 1280, 720) },
      { id: "img-008b", isPrimary: false, alt: "Side view", ...thumb("ui-008b", 1280, 720) },
    ],
    sourceFile: { name: "iphone-15-pro-mockups.zip", size: 380 * 1024 * 1024, url: "/files/iphone-15-pro-mockups.zip" },
    tags: ["mockup", "iphone", "psd", "apple"],
    specifications: ["12 Angles", "PSD Smart Object", "4000x6000px", "RGB Color"],
    whatsIncluded: ["12 PSD files", "PDF instructions"],
    featured: false,
    enableReview: true,
    downloadLimit: 3,
    metaTitle: "iPhone 15 Pro Mockup Pack - 12 Angle PSD",
    metaDescription: "Mockup iPhone 15 Pro 12 angle dengan PSD smart object resolusi tinggi.",
    viewCount: 678,
    soldCount: 78,
    rating: 4.7,
    reviewCount: 42,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(8),
    publishedAt: daysAgo(45),
  },
  {
    id: "prod-009",
    slug: "macbook-workspace-mockups",
    title: "MacBook Workspace Mockups",
    description: "Mockup MacBook Pro & Air dalam setup workspace yang estetik. Cocok untuk presentasi produk digital.",
    shortDescription: "Mockup MacBook Pro & Air dalam setup workspace estetik, PSD smart object.",
    productType: "physical",
    category: "mockups",
    status: "out_of_stock",
    creator: { id: "cr-006", name: "Mockup Studio", title: "Mockup Specialist" },
    price: 89000,
    isFree: false,
    discount: null,
    stock: 0,
    sku: "MK-MS-009",
    weight: 500,
    dimensions: "30 × 20 × 5 cm",
    thumbnail: { id: "img-009", isPrimary: true, alt: "MacBook Mockup", ...thumb("ui-009", 800, 600) },
    gallery: [
      { id: "img-009a", isPrimary: true, alt: "Workspace", ...thumb("ui-009a", 1280, 720) },
    ],
    sourceFile: { name: "macbook-workspace-mockups.zip", size: 420 * 1024 * 1024, url: "/files/macbook-workspace-mockups.zip" },
    tags: ["mockup", "macbook", "psd", "workspace"],
    specifications: ["8 Setup", "PSD Smart Object", "5000x3000px"],
    whatsIncluded: ["8 PSD files"],
    featured: false,
    enableReview: true,
    downloadLimit: 3,
    metaTitle: "MacBook Workspace Mockups",
    metaDescription: "Mockup MacBook workspace estetik untuk presentasi produk digital.",
    viewCount: 234,
    soldCount: 23,
    rating: 4.5,
    reviewCount: 12,
    createdAt: daysAgo(70),
    updatedAt: daysAgo(15),
    publishedAt: daysAgo(68),
  },
  {
    id: "prod-010",
    slug: "auth-api-boilerplate",
    title: "Authentication API Boilerplate",
    description: "Boilerplate API authentication dengan JWT, OAuth (Google, GitHub), 2FA, dan rate limiting. Built dengan Node.js + Express.",
    shortDescription: "Boilerplate auth API: JWT, OAuth Google/GitHub, 2FA, rate limiting.",
    productType: "digital",
    category: "source_code",
    status: "draft",
    creator: { id: "cr-005", name: "CodeMaster ID", title: "Dev Studio", studioName: "CodeMaster" },
    price: 0,
    isFree: true,
    discount: null,
    stock: 999,
    sku: "SC-CM-010",
    weight: 0,
    thumbnail: { id: "img-010", isPrimary: true, alt: "Auth API", ...thumb("ui-010", 800, 600) },
    gallery: [
      { id: "img-010a", isPrimary: true, alt: "Code preview", ...thumb("ui-010a", 1280, 720) },
    ],
    sourceFile: { name: "auth-api-boilerplate.zip", size: 1.5 * 1024 * 1024, url: "/files/auth-api-boilerplate.zip" },
    demoUrl: "https://github.com/codemaster/auth-api",
    tags: ["nodejs", "api", "auth", "jwt", "free"],
    specifications: ["Node.js + Express", "JWT + OAuth", "2FA Support", "Rate Limiting", "TypeScript"],
    whatsIncluded: ["Source code", "Postman collection", "Documentation"],
    featured: false,
    enableReview: true,
    downloadLimit: undefined,
    metaTitle: "Authentication API Boilerplate - JWT + OAuth",
    metaDescription: "Boilerplate auth API Node.js dengan JWT, OAuth, 2FA. Gratis!",
    viewCount: 0,
    soldCount: 0,
    rating: 0,
    reviewCount: 0,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
    publishedAt: null,
  },
];
